export interface UserStory {
  id: string;
  module: string;
  subModule: string;
  feature: string;
  outcome: string;
  grouping: string;
  custom: string;
  setupComments: string;
  status: string;
}

export const MODULE_COLORS: Record<string, string> = {
  "Product Management": "#EBF5FB",
  "Business Management": "#EAFAF1",
  "Order Management": "#FEF9E7",
  "Reports & Analytics": "#F5EEF8",
  "Wallet Management": "#FDEDEC",
  "Advertisement Management": "#E8F8F5",
  "Employee Management": "#FDF2E9",
  "Item / Inventory Mgmt": "#F0F3FF",
  "Marketing & Promotions": "#EFF5FB",
  "Zone & Module Setup": "#F9EBEA",
  "Business Settings": "#EAECEE",
  "Financial Operations": "#E8DAEF",
  "Gallery & Media": "#FDFEFE",
};

export const USER_STORIES: UserStory[] = [
  {
    id: 'PM-CAT-001',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'Add a new product category with a name and a 1:1 ratio image in multiple languages (Default, English, Arabic)',
    outcome: 'The category is created and appears in the master category list, enabling products to be assigned to it',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: 'Multilingual name fields (Default / EN / AR) and image upload required',
    status: 'Open',
  },
  {
    id: 'PM-CAT-002',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'View the full category list with search and export controls',
    outcome: 'I can quickly locate any category and export the list to Excel for audit purposes',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CAT-003',
    module: 'Product Management',
    subModule: 'Categories',
    feature: "Edit an existing category's name or image",
    outcome: 'Category information stays accurate without having to delete and recreate entries',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CAT-004',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'Enable or disable a category using a status toggle',
    outcome: 'Hidden categories stop appearing in all product assignment dropdowns and customer storefronts instantly',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CAT-005',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'Delete a category that has no linked products',
    outcome: 'Stale or test categories are removed, keeping the catalogue clean',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-SUB-001',
    module: 'Product Management',
    subModule: 'Sub Categories',
    feature: 'Add a new sub-category by selecting a parent main category and entering a name in all supported languages',
    outcome: 'Products can be nested under a main category for finer classification, improving shopability',
    grouping: 'PM-SubCat',
    custom: 'No',
    setupComments: 'Parent category must exist before creating sub-category',
    status: 'Open',
  },
  {
    id: 'PM-SUB-002',
    module: 'Product Management',
    subModule: 'Sub Categories',
    feature: 'View the sub-category list showing each sub-category alongside its parent category',
    outcome: 'I can verify the correct parent-child relationships at a glance',
    grouping: 'PM-SubCat',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-SUB-003',
    module: 'Product Management',
    subModule: 'Sub Categories',
    feature: "Edit a sub-category's name or reassign it to a different parent category",
    outcome: 'Mis-classified sub-categories can be corrected without data loss',
    grouping: 'PM-SubCat',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BIM-001',
    module: 'Product Management',
    subModule: 'Categories – Bulk Import',
    feature: 'Download the official category bulk-import Excel template (with or without current data)',
    outcome: 'I have a correctly formatted file to fill in, preventing import errors',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Template must be .xls or .xlsx format',
    status: 'Open',
  },
  {
    id: 'PM-BIM-002',
    module: 'Product Management',
    subModule: 'Categories – Bulk Import',
    feature: 'Upload a completed Excel file to import multiple new categories at once',
    outcome: 'Onboarding large category structures is done in minutes instead of hours of manual entry',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Upload New Data option selected',
    status: 'Open',
  },
  {
    id: 'PM-BIM-003',
    module: 'Product Management',
    subModule: 'Categories – Bulk Import',
    feature: 'Upload a completed Excel file to update existing category records in bulk',
    outcome: 'Mass corrections to names, images, or status are applied without editing each record individually',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Update Existing Data option selected',
    status: 'Open',
  },
  {
    id: 'PM-BEX-001',
    module: 'Product Management',
    subModule: 'Categories – Bulk Export',
    feature: 'Export the full category and sub-category list as an Excel file with optional sort/filter options',
    outcome: 'I have an offline backup or a starting-point file for preparing the next bulk import',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ATT-001',
    module: 'Product Management',
    subModule: 'Attributes',
    feature: 'Add a new product attribute (e.g., Colour, Material, Finish) with multilingual name support',
    outcome: 'Descriptive characteristics can be attached to products, enriching customer-facing detail pages',
    grouping: 'PM-Attributes',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ATT-002',
    module: 'Product Management',
    subModule: 'Attributes',
    feature: 'View all attributes in a list and edit or delete individual attributes',
    outcome: 'The attribute dictionary stays current as product lines evolve',
    grouping: 'PM-Attributes',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-UNT-001',
    module: 'Product Management',
    subModule: 'Units',
    feature: 'Add a new unit of measurement (e.g., kg, piece, metre, litre) with multilingual name support',
    outcome: 'Products can specify the correct selling unit, avoiding customer confusion',
    grouping: 'PM-Units',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-UNT-002',
    module: 'Product Management',
    subModule: 'Units',
    feature: 'View the units list and edit or delete entries',
    outcome: 'Outdated or duplicate units are removed, ensuring only valid options appear in product forms',
    grouping: 'PM-Units',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BRD-001',
    module: 'Product Management',
    subModule: 'Brands',
    feature: 'Add a new brand with a name and an uploaded brand logo',
    outcome: 'Products can be associated with a recognisable brand, building customer trust',
    grouping: 'PM-Brands',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BRD-002',
    module: 'Product Management',
    subModule: 'Brands',
    feature: 'Enable or disable a brand using a status toggle',
    outcome: 'Discontinued brands are hidden from product forms without losing historical data',
    grouping: 'PM-Brands',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BRD-003',
    module: 'Product Management',
    subModule: 'Brands',
    feature: 'View and search the full brand list',
    outcome: 'I can quickly find any brand in a growing catalogue without scrolling',
    grouping: 'PM-Brands',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-001',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Enter product name, short description, and long description in Default, English, and Arabic',
    outcome: 'The product page is fully localised for all supported customer markets',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'All three language tabs should be completed',
    status: 'Open',
  },
  {
    id: 'PM-PRD-002',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Upload a full-size 1:1 product image and a required thumbnail image',
    outcome: 'Customers see a high-quality visual and the thumbnail renders correctly in listing grids',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Thumbnail is mandatory; full image is recommended',
    status: 'Open',
  },
  {
    id: 'PM-PRD-003',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Assign the product to a store, category, sub-category, and brand',
    outcome: 'The product appears in the correct storefront, category page, and brand filter',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Store and Category fields are mandatory',
    status: 'Open',
  },
  {
    id: 'PM-PRD-004',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Select the unit of measurement and set a maximum purchase quantity limit per order',
    outcome: 'Customers buy the correct measured unit and bulk purchases beyond the limit are blocked at checkout',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-005',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Set the product price, current stock quantity, and a discount percentage',
    outcome: 'The price, discounted price, and remaining stock are displayed accurately on the customer app',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-006',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Add product attributes such as colour, material, and size',
    outcome: 'Customers can filter and search by specific product characteristics',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-007',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Import product information from the platform gallery to pre-fill image fields',
    outcome: 'Reusing existing gallery assets avoids duplicate uploads and speeds up listing',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Add Info From Gallery feature',
    status: 'Open',
  },
  {
    id: 'PM-PRD-008',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Save the product as Draft without publishing it to the storefront',
    outcome: 'I can prepare a product in advance and review it before making it live',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-009',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Publish the product to make it live and visible to customers immediately',
    outcome: 'New products become available for purchase without any additional admin steps',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: "Requires admin approval if 'Need Approval For Products' is enabled",
    status: 'Open',
  },
  {
    id: 'PM-LST-001',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'View the complete product list with search, filter by category/status, and paginate results',
    outcome: 'I can find any product instantly even with thousands of SKUs',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-002',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'Edit any field of an existing product directly from the list view',
    outcome: 'Corrections to price, stock, descriptions, or images are applied without re-creating the listing',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-003',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'Enable or disable a product using the status toggle',
    outcome: 'Out-of-season or out-of-stock products are hidden from customers without permanent deletion',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-004',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'Delete a product permanently from the catalogue',
    outcome: 'Discontinued SKUs are removed cleanly, freeing up catalogue space',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Action is irreversible',
    status: 'Open',
  },
  {
    id: 'PM-LOW-001',
    module: 'Product Management',
    subModule: 'Product Setup – Low Stock',
    feature: 'View a filtered list of all products whose stock quantity is at or below the low-stock threshold',
    outcome: 'I can prioritise reordering before products go out of stock and cause lost sales',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LOW-002',
    module: 'Product Management',
    subModule: 'Product Setup – Low Stock',
    feature: 'Update the stock quantity of a low-stock product directly from the low-stock list',
    outcome: 'I can top up inventory without navigating through the full product editor',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-REV-001',
    module: 'Product Management',
    subModule: 'Product Setup – Reviews',
    feature: 'View all customer reviews submitted for products, including rating, comment, and reviewer name',
    outcome: 'I have visibility over product satisfaction across the entire catalogue',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-REV-002',
    module: 'Product Management',
    subModule: 'Product Setup – Reviews',
    feature: 'Delete an inappropriate or fraudulent product review',
    outcome: 'Fake or abusive reviews are removed before they damage product reputation',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PIB-001',
    module: 'Product Management',
    subModule: 'Product Setup – Bulk Import',
    feature: 'Download the product bulk-import Excel template pre-filled with existing product data',
    outcome: 'I can use the exported file as a base for updates rather than starting from scratch',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PIB-002',
    module: 'Product Management',
    subModule: 'Product Setup – Bulk Import',
    feature: 'Import a filled Excel file to add hundreds of new products in a single operation',
    outcome: 'Mass product onboarding is completed in minutes with zero manual form filling',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Only .xls/.xlsx accepted; all mandatory columns must be filled',
    status: 'Open',
  },
  {
    id: 'PM-PEX-001',
    module: 'Product Management',
    subModule: 'Product Setup – Bulk Export',
    feature: 'Export the full product catalogue to Excel for reporting, backup, or external sharing',
    outcome: 'I always have an up-to-date offline copy of the product database for compliance or handover',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-001',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Draw a new operational zone boundary on the interactive Google Map and name it in multiple languages',
    outcome: 'A precise geographic service area is defined so stores and deliveries can be restricted to that region',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: 'Both polygon drawing and zone name are mandatory',
    status: 'Open',
  },
  {
    id: 'ZN-002',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'View, search, and export all existing zones in the zone management list',
    outcome: 'I have a clear overview of every service region and can audit them at any time',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-003',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Enable or disable an entire zone using the master status toggle',
    outcome: 'All storefronts, deliveries, and customer access in a problematic region can be suspended instantly',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: 'Disabling a zone removes it from the customer app in real time',
    status: 'Open',
  },
  {
    id: 'ZN-004',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Connect a business module to a zone using the grid action icon',
    outcome: 'The zone starts offering the selected type of services (e.g., eCommerce) to customers in that area',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: 'A zone without a connected module offers no services',
    status: 'Open',
  },
  {
    id: 'ZN-005',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Edit the drawn boundary polygon of an existing zone',
    outcome: 'Service area adjustments are reflected immediately without recreating the zone from scratch',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-001',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: 'Create a new business module type (Grocery, Food, Pharmacy, eCommerce, Parcel) with name, description, icon, and thumbnail',
    outcome: 'A new vertical is available for stores to register under and for customers to browse on the home screen',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: 'Module type cannot be changed after creation',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-002',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: 'Filter the module list by module type and search by name',
    outcome: 'I can locate specific modules instantly as the platform scales to many business verticals',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-003',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: 'Enable or disable a business module to control its visibility on the customer app home screen',
    outcome: 'A module under maintenance or review is hidden until it is ready',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: 'Disabling hides all stores under this module',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-004',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: "Edit a module's name, description, icon, or thumbnail after initial creation",
    outcome: 'Branding and descriptions stay accurate as the business evolves without recreating the module',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-001',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Set global company name, email, phone, country, address, and map coordinates as platform defaults',
    outcome: 'All receipts, emails, and the customer app default map reflect the correct company identity',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Latitude and longitude set the default map centre for new users',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-002',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Upload the platform logo (3:1 ratio) and favicon (1:1 ratio)',
    outcome: 'The brand identity is consistently displayed across the admin dashboard, web portal, and browser tabs',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-003',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Configure time zone, time format, currency symbol, currency position, and decimal precision',
    outcome: 'All financial figures, order timestamps, and discount windows reflect the correct local standards',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Currency and decimal changes affect all displayed prices immediately',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-004',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Activate Maintenance Mode to disable all customer-facing apps and APIs during critical updates',
    outcome: 'Customers see a maintenance screen and cannot place orders during planned downtime, protecting data integrity',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Only Admin panel remains accessible in maintenance mode',
    status: 'Open',
  },
  {
    id: 'BS-VND-001',
    module: 'Business Settings',
    subModule: 'Vendor Settings',
    feature: 'Enable or disable vendor self-registration so external users can apply to become store owners',
    outcome: 'I control whether the vendor network grows organically or only through admin invitation',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-VND-002',
    module: 'Business Settings',
    subModule: 'Vendor Settings',
    feature: 'Enable product approval workflow so every new vendor product requires admin review before going live',
    outcome: 'Platform quality is maintained by preventing unapproved or low-quality products from reaching customers',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Can be applied for: Add new product, Update price, Update details',
    status: 'Open',
  },
  {
    id: 'BS-VND-003',
    module: 'Business Settings',
    subModule: 'Vendor Settings',
    feature: 'Allow or prevent vendors from cancelling orders',
    outcome: 'Order fulfilment policies are enforced consistently, reducing customer disappointment',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-VND-004',
    module: 'Business Settings',
    subModule: 'Vendor Settings',
    feature: 'Allow vendors to publicly reply to customer product reviews',
    outcome: 'Vendor engagement with feedback boosts customer trust and platform transparency',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-VND-005',
    module: 'Business Settings',
    subModule: 'Vendor Settings',
    feature: 'Configure Cash-In-Hand Overflow thresholds to restrict vendors holding too much unremitted cash',
    outcome: 'Cash flow risks from COD are managed automatically without manual intervention',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Set maximum amount and minimum repayment values',
    status: 'Open',
  },
  {
    id: 'BS-DLV-001',
    module: 'Business Settings',
    subModule: 'Deliveryman Settings',
    feature: 'Set the maximum number of orders a single delivery driver can carry simultaneously',
    outcome: 'No driver can accept more jobs than they can handle, ensuring on-time deliveries',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-DLV-002',
    module: 'Business Settings',
    subModule: 'Deliveryman Settings',
    feature: 'Enable photo proof of delivery, requiring drivers to capture an image before marking orders as Delivered',
    outcome: 'Disputes about non-delivery are resolved with photographic evidence in every case',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-DLV-003',
    module: 'Business Settings',
    subModule: 'Deliveryman Settings',
    feature: 'Enable the customer tipping feature for delivery drivers during checkout',
    outcome: 'Drivers earn additional gratuity, improving fleet retention and morale',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-DLV-004',
    module: 'Business Settings',
    subModule: 'Deliveryman Settings',
    feature: 'Allow or prevent drivers from registering on the platform independently',
    outcome: 'I control the fleet size and vet drivers before they join the delivery network',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-CUS-001',
    module: 'Business Settings',
    subModule: 'Customer & Wallet',
    feature: 'Enable the customer wallet feature so users can store balance and receive refunds in-app',
    outcome: 'Refunds and pre-loaded funds remain within the platform, improving reinvestment rates',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-CUS-002',
    module: 'Business Settings',
    subModule: 'Customer & Wallet',
    feature: 'Configure loyalty points: earning percentage per order, point-to-currency conversion rate, and minimum redemption threshold',
    outcome: 'A gamified rewards system boosts repeat purchases without manual coupon management',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Example: 2% earn rate, 100 points = 1 BHD, minimum 500 points to redeem',
    status: 'Open',
  },
  {
    id: 'BS-CUS-003',
    module: 'Business Settings',
    subModule: 'Customer & Wallet',
    feature: 'Enable the referral program so existing customers earn rewards for inviting new users',
    outcome: 'Customer acquisition is driven virally through word-of-mouth at low marketing cost',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-REF-001',
    module: 'Business Settings',
    subModule: 'Refund Settings',
    feature: 'Enable or disable the global refund request feature for customers',
    outcome: 'I can open or freeze the refund system depending on operational capacity',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-REF-002',
    module: 'Business Settings',
    subModule: 'Refund Settings',
    feature: 'Set the refund eligibility window in days after a delivery is completed',
    outcome: 'Only orders within the allowed time window can request refunds, preventing abuse',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-REF-003',
    module: 'Business Settings',
    subModule: 'Refund Settings',
    feature: 'Add, edit, or delete refund reason options shown to customers during the refund flow',
    outcome: 'Refund data is categorised accurately for analytics and dispute resolution',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Examples: Damaged item, Missing item, Wrong order',
    status: 'Open',
  },
  {
    id: 'BS-LNG-001',
    module: 'Business Settings',
    subModule: 'Language Setup',
    feature: 'Add a new platform language specifying the ISO language code and text direction (LTR or RTL)',
    outcome: 'The platform becomes accessible to a new language market immediately',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'RTL setting flips the entire app UI for Arabic/Hebrew',
    status: 'Open',
  },
  {
    id: 'BS-LNG-002',
    module: 'Business Settings',
    subModule: 'Language Setup',
    feature: 'Set a language as the default for new customer sessions',
    outcome: 'All first-time visitors see the platform in the most appropriate language for the market',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-TAX-001',
    module: 'Business Settings',
    subModule: 'System Tax',
    feature: 'Create a new tax type with a name and percentage rate (e.g., VAT 5%)',
    outcome: 'Taxes are available for assignment to orders or products, ensuring regulatory compliance',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Tax name appears on customer invoices',
    status: 'Open',
  },
  {
    id: 'BS-TAX-002',
    module: 'Business Settings',
    subModule: 'System Tax',
    feature: 'Configure whether tax is calculated inclusive (baked into price) or exclusive (added on top) of product prices',
    outcome: 'Customers see the correct pricing model expected by local consumer protection regulations',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-SUB-001',
    module: 'Business Settings',
    subModule: 'Subscription Management',
    feature: 'Create subscription packages with name, price, validity period, and available features checklist',
    outcome: 'Vendors are offered tiered plans that gate features based on their subscription level',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Features: POS, self-delivery, app access, reviews, chat',
    status: 'Open',
  },
  {
    id: 'BS-SUB-002',
    module: 'Business Settings',
    subModule: 'Subscription Management',
    feature: 'Set maximum order and product limits per subscription package',
    outcome: 'Vendors are incentivised to upgrade their plan when they hit operational limits',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-SUB-003',
    module: 'Business Settings',
    subModule: 'Subscription Management',
    feature: 'Configure a free trial period so new vendors can evaluate the platform before committing to a paid plan',
    outcome: 'Vendor acquisition is easier with a risk-free onboarding pathway',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-PGS-001',
    module: 'Business Settings',
    subModule: 'Pages & Social Media',
    feature: 'Edit the Terms & Conditions, Privacy Policy, Refund Policy, Cancellation Policy, and About Us pages using the rich-text editor',
    outcome: 'Legal and informational pages are always up to date and visible to customers',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'All pages support multilingual content',
    status: 'Open',
  },
  {
    id: 'BS-PGS-002',
    module: 'Business Settings',
    subModule: 'Pages & Social Media',
    feature: 'Add or update social media links (Facebook, Instagram, Twitter, LinkedIn) shown in the platform footer',
    outcome: 'Customers can follow the brand on their preferred social channel directly from the app or website',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-GAL-001',
    module: 'Business Settings',
    subModule: 'Gallery',
    feature: 'Browse the centralised gallery file explorer organised into system folders (Products, Store, Banner, Category, etc.)',
    outcome: 'I can locate any uploaded file quickly without searching through individual sections',
    grouping: 'BS-Gallery',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-GAL-002',
    module: 'Business Settings',
    subModule: 'Gallery',
    feature: 'Upload individual images or a zip archive of multiple images to the gallery',
    outcome: 'New visual assets are stored centrally and available to reuse across the entire platform',
    grouping: 'BS-Gallery',
    custom: 'No',
    setupComments: 'Zip upload auto-extracts all contained images',
    status: 'Open',
  },
  {
    id: 'BS-GAL-003',
    module: 'Business Settings',
    subModule: 'Gallery',
    feature: 'Preview, copy the direct URL, download, or delete any file in the gallery',
    outcome: 'Asset management is efficient and I can share or embed gallery URLs in external tools',
    grouping: 'BS-Gallery',
    custom: 'No',
    setupComments: 'Delete action is permanent and irreversible',
    status: 'Open',
  },
  {
    id: 'BS-WBS-001',
    module: 'Business Settings',
    subModule: 'Websocket Config',
    feature: 'Configure the websocket server URL and port for real-time order tracking and push notifications',
    outcome: 'Live driver tracking on the map and instant alerts function correctly for all app users',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Only change with DevOps guidance; errors break live tracking',
    status: 'Open',
  },
  {
    id: 'BS-LND-001',
    module: 'Business Settings',
    subModule: 'Landing Page',
    feature: 'Edit the header title, subtitle, hero banner image, and marketing content blocks on the customer web landing page',
    outcome: 'The public-facing web portal reflects current promotions and brand messaging accurately',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-001',
    module: 'Order Management',
    subModule: 'Order List',
    feature: 'View a real-time list of all orders showing order ID, customer name, total, status, and date',
    outcome: 'I have full visibility of every transaction in a single view without missing any incoming order',
    grouping: 'OM-Orders',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-002',
    module: 'Order Management',
    subModule: 'Order List',
    feature: 'Filter orders by status (Pending, Confirmed, Packed, Dispatched, Delivered, Cancelled, Returned)',
    outcome: 'I see only the orders requiring action at each stage of the fulfilment workflow',
    grouping: 'OM-Orders',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-003',
    module: 'Order Management',
    subModule: 'Order List',
    feature: 'Filter orders by date range and search by customer name or order ID',
    outcome: 'I can locate any specific order instantly for customer service or accounting purposes',
    grouping: 'OM-Orders',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-004',
    module: 'Order Management',
    subModule: 'Order Processing',
    feature: 'Accept a new order with a single click to move it from Pending to Confirmed',
    outcome: 'The customer receives an instant confirmation notification and I commit to fulfilling the order',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-005',
    module: 'Order Management',
    subModule: 'Order Processing',
    feature: 'Reject an incoming order and provide a reason (e.g., out of stock, cannot deliver to address)',
    outcome: 'The customer is informed promptly without waiting indefinitely, and the reason is logged for analysis',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-006',
    module: 'Order Management',
    subModule: 'Order Processing',
    feature: 'Update the order stage sequentially: Confirmed → Packed → Dispatched → Delivered',
    outcome: 'Customers receive a live status update at every milestone, reducing customer service enquiries',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-007',
    module: 'Order Management',
    subModule: 'Order Details',
    feature: 'View the complete order detail page including all line items, quantities, customer address, and selected payment method',
    outcome: 'I have all information needed to fulfil the order correctly without contacting the customer',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-008',
    module: 'Order Management',
    subModule: 'Order Details',
    feature: 'Generate and download or print an invoice or delivery note for the order',
    outcome: 'Proper paperwork accompanies each delivery and is available for accounting reconciliation',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-RET-001',
    module: 'Order Management',
    subModule: 'Returns & Refunds',
    feature: 'Initiate a return or refund for an eligible delivered order within the configured refund window',
    outcome: 'Customer disputes are handled through a structured process rather than ad hoc conversations',
    grouping: 'OM-Returns',
    custom: 'No',
    setupComments: 'Refund window is configured in Business Settings',
    status: 'Open',
  },
  {
    id: 'OM-RET-002',
    module: 'Order Management',
    subModule: 'Returns & Refunds',
    feature: 'Approve or deny a customer refund request and log the admin decision with notes',
    outcome: 'Refund decisions are documented and the customer wallet is updated automatically upon approval',
    grouping: 'OM-Returns',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-RET-003',
    module: 'Order Management',
    subModule: 'Returns & Refunds',
    feature: 'View the complete returns list filtered by status (Pending, Approved, Denied)',
    outcome: 'I can monitor the volume and nature of returns to identify product quality issues',
    grouping: 'OM-Returns',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-DAS-001',
    module: 'Reports & Analytics',
    subModule: 'Dashboard',
    feature: 'View a summary dashboard showing total orders, revenue, active stores, and registered customers for the current period',
    outcome: 'I get an instant health-check of the platform without running individual reports',
    grouping: 'RA-Dashboard',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-SAL-001',
    module: 'Reports & Analytics',
    subModule: 'Sales Report',
    feature: 'Filter the sales report by a custom date range, or by preset periods (today, this week, this month, this year)',
    outcome: 'I can analyse revenue performance for any specific period to identify trends or seasonal patterns',
    grouping: 'RA-Sales',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-SAL-002',
    module: 'Reports & Analytics',
    subModule: 'Sales Report',
    feature: 'View revenue broken down by business module, store, or product category',
    outcome: 'I can identify which segments of the business are driving the most income and allocate resources accordingly',
    grouping: 'RA-Sales',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-PRD-001',
    module: 'Reports & Analytics',
    subModule: 'Product Report',
    feature: 'View a top-selling products report ranked by quantity sold and revenue generated',
    outcome: 'I can prioritise restocking and marketing for my best performers',
    grouping: 'RA-Products',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-PRD-002',
    module: 'Reports & Analytics',
    subModule: 'Product Report',
    feature: 'View a low-performing or zero-sales product report',
    outcome: 'I can make informed decisions about discontinuing or promoting underperforming SKUs',
    grouping: 'RA-Products',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-CUS-001',
    module: 'Reports & Analytics',
    subModule: 'Customer Report',
    feature: 'View customer acquisition data showing new registrations over time',
    outcome: 'I understand growth trends and the effectiveness of marketing campaigns',
    grouping: 'RA-Customers',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-CUS-002',
    module: 'Reports & Analytics',
    subModule: 'Customer Report',
    feature: 'View repeat purchase rates and identify loyal customer segments',
    outcome: 'I can target loyalty campaigns at customers with high lifetime value',
    grouping: 'RA-Customers',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-STR-001',
    module: 'Reports & Analytics',
    subModule: 'Store Report',
    feature: 'View per-store performance metrics including orders completed, revenue, and cancellation rate',
    outcome: 'Underperforming stores are identified early and can be supported or reviewed',
    grouping: 'RA-Stores',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-DEL-001',
    module: 'Reports & Analytics',
    subModule: 'Delivery Report',
    feature: 'View delivery performance metrics including average delivery time, on-time rate, and driver performance scores',
    outcome: 'Fleet efficiency issues are identified and driver training or routing can be improved',
    grouping: 'RA-Delivery',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-TXN-001',
    module: 'Reports & Analytics',
    subModule: 'Transaction Report',
    feature: 'View a full financial transaction log including payments, refunds, wallet credits, and commissions',
    outcome: 'Every monetary movement is auditable and reconcilable against bank records',
    grouping: 'RA-Transactions',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-EXP-001',
    module: 'Reports & Analytics',
    subModule: 'Export',
    feature: 'Export any report view as an Excel (.xlsx) or CSV file for offline analysis or sharing',
    outcome: 'Reports are available in standard formats for accountants, partners, or management decks',
    grouping: 'RA-Export',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'WM-BAL-001',
    module: 'Wallet Management',
    subModule: 'Balance & Overview',
    feature: 'View my current wallet balance, amount pending clearance, and total amount available for withdrawal',
    outcome: 'I always know my exact financial position without checking my bank account',
    grouping: 'WM-Balance',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'WM-WTH-001',
    module: 'Wallet Management',
    subModule: 'Withdrawal',
    feature: 'Submit a withdrawal request specifying the amount and the registered payment method (bank transfer, mobile money, etc.)',
    outcome: 'I can transfer my earned platform balance to my real bank account when needed',
    grouping: 'WM-Withdrawal',
    custom: 'No',
    setupComments: 'Available withdrawal methods are configured by admin',
    status: 'Open',
  },
  {
    id: 'WM-WTH-002',
    module: 'Wallet Management',
    subModule: 'Withdrawal',
    feature: 'Track the status of my withdrawal request (Pending, Approved, Denied)',
    outcome: 'I know whether my payout has been processed without contacting support',
    grouping: 'WM-Withdrawal',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'WM-HIS-001',
    module: 'Wallet Management',
    subModule: 'Transaction History',
    feature: 'View a paginated transaction history listing every credit and debit with date, amount, type, and reference',
    outcome: 'I can reconcile all wallet movements and dispute any discrepancy with clear evidence',
    grouping: 'WM-History',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'WM-HIS-002',
    module: 'Wallet Management',
    subModule: 'Transaction History',
    feature: 'Filter transaction history by type (Order credit, Refund deduction, Commission, Manual adjustment)',
    outcome: 'I can quickly isolate specific transaction types for financial review or tax preparation',
    grouping: 'WM-History',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'WM-AUT-001',
    module: 'Wallet Management',
    subModule: 'Auto-Credits',
    feature: 'Receive an automatic wallet credit when an order assigned to me is marked as Delivered by the driver',
    outcome: 'Earnings are settled without manual intervention, eliminating delays and billing disputes',
    grouping: 'WM-AutoSettle',
    custom: 'No',
    setupComments: 'Settlement timing is configured in Business Settings',
    status: 'Open',
  },
  {
    id: 'WM-REF-001',
    module: 'Wallet Management',
    subModule: 'Refund Deductions',
    feature: 'See refund deductions from my wallet when an admin approves a customer return for my order',
    outcome: 'The financial impact of returns is shown transparently so I can manage cash flow',
    grouping: 'WM-Refunds',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'WM-MTH-001',
    module: 'Wallet Management',
    subModule: 'Withdraw Methods',
    feature: 'Add a preferred withdrawal method (bank account details, IBAN, mobile wallet number) to my profile',
    outcome: 'Withdrawal requests always route to the correct account without re-entering details each time',
    grouping: 'WM-Methods',
    custom: 'No',
    setupComments: 'Available method types are set by the platform admin',
    status: 'Open',
  },
  {
    id: 'AD-CMP-001',
    module: 'Advertisement Management',
    subModule: 'Campaign Creation',
    feature: 'Create a new advertisement campaign by selecting an ad format (banner, product spotlight, featured store)',
    outcome: 'My products or store are promoted to targeted shoppers through the most appropriate ad placement',
    grouping: 'AD-Create',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-CMP-002',
    module: 'Advertisement Management',
    subModule: 'Campaign Creation',
    feature: 'Configure campaign target audience settings (zone, module, customer segment)',
    outcome: 'The ad reaches only the shoppers most likely to convert in my specific service area',
    grouping: 'AD-Create',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-BDG-001',
    module: 'Advertisement Management',
    subModule: 'Budget & Schedule',
    feature: 'Set a daily spending cap and/or a total campaign budget limit',
    outcome: 'My advertising spend stays within the approved budget without manual monitoring',
    grouping: 'AD-Budget',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-BDG-002',
    module: 'Advertisement Management',
    subModule: 'Budget & Schedule',
    feature: 'Schedule campaign start and end dates and times',
    outcome: 'Promotions run automatically during peak periods without manual activation or deactivation',
    grouping: 'AD-Budget',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-CTL-001',
    module: 'Advertisement Management',
    subModule: 'Campaign Control',
    feature: 'Pause a running campaign temporarily without losing its settings or progress',
    outcome: 'I can halt spending during slow periods and resume instantly when activity picks up',
    grouping: 'AD-Control',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-CTL-002',
    module: 'Advertisement Management',
    subModule: 'Campaign Control',
    feature: 'Stop a campaign permanently and archive its performance data',
    outcome: 'Completed campaigns are stored for reference when planning future promotions',
    grouping: 'AD-Control',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-ANL-001',
    module: 'Advertisement Management',
    subModule: 'Performance Analytics',
    feature: 'View impressions, clicks, click-through rate (CTR), and conversion count for each campaign',
    outcome: 'I can evaluate which ad formats and targeting settings deliver the best return on investment',
    grouping: 'AD-Analytics',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'AD-ANL-002',
    module: 'Advertisement Management',
    subModule: 'Performance Analytics',
    feature: 'Compare performance across multiple campaigns in a single report view',
    outcome: 'I can determine the most cost-effective advertising strategy by comparing campaign results side by side',
    grouping: 'AD-Analytics',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-INV-001',
    module: 'Employee Management',
    subModule: 'Employee Invitations',
    feature: 'Invite a new staff member by entering their email address and selecting a predefined role',
    outcome: 'Team members receive access credentials without me sharing my owner account login',
    grouping: 'EM-Users',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-INV-002',
    module: 'Employee Management',
    subModule: 'Employee Invitations',
    feature: 'Resend an invitation email to an employee who has not yet accepted access',
    outcome: 'Onboarding is not blocked if the original invitation email was missed or expired',
    grouping: 'EM-Users',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-ROL-001',
    module: 'Employee Management',
    subModule: 'Role Management',
    feature: 'Create a custom role with a specific combination of module-level permissions (view, edit, delete, export)',
    outcome: 'Each team member only accesses the sections relevant to their job, reducing security and error risk',
    grouping: 'EM-Roles',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-ROL-002',
    module: 'Employee Management',
    subModule: 'Role Management',
    feature: 'Edit an existing role to add or remove permissions',
    outcome: 'Access levels evolve with job responsibilities without needing to recreate roles from scratch',
    grouping: 'EM-Roles',
    custom: 'No',
    setupComments: 'Changes apply immediately to all employees assigned the role',
    status: 'Open',
  },
  {
    id: 'EM-ROL-003',
    module: 'Employee Management',
    subModule: 'Role Management',
    feature: 'Delete a custom role that is no longer in use',
    outcome: 'Unused roles do not clutter the permission system or create accidental access grants',
    grouping: 'EM-Roles',
    custom: 'No',
    setupComments: 'Role must have no assigned employees before deletion',
    status: 'Open',
  },
  {
    id: 'EM-LST-001',
    module: 'Employee Management',
    subModule: 'Employee List',
    feature: 'View a list of all active employees showing name, email, assigned role, and last login date',
    outcome: 'I have a clear at-a-glance picture of who has access and what they are authorised to do',
    grouping: 'EM-Users',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-LST-002',
    module: 'Employee Management',
    subModule: 'Employee List',
    feature: 'Search the employee list by name or email address',
    outcome: 'I can find a specific team member instantly in a large organisation',
    grouping: 'EM-Users',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-ACC-001',
    module: 'Employee Management',
    subModule: 'Access Control',
    feature: "Deactivate an employee's account immediately upon their departure",
    outcome: 'Platform access is revoked in real time, protecting sensitive store and customer data',
    grouping: 'EM-Access',
    custom: 'No',
    setupComments: 'Deactivated accounts cannot log in but records are preserved',
    status: 'Open',
  },
  {
    id: 'EM-ACC-002',
    module: 'Employee Management',
    subModule: 'Access Control',
    feature: 'Reactivate a previously deactivated employee account',
    outcome: 'Returning contractors or re-hired staff are re-enabled without recreating their profile',
    grouping: 'EM-Access',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-AUD-001',
    module: 'Employee Management',
    subModule: 'Activity Audit',
    feature: 'View an activity log of all actions performed by each employee (records created, orders modified, settings changed)',
    outcome: 'I can hold team members accountable and investigate any data discrepancy with a timestamped audit trail',
    grouping: 'EM-Audit',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'EM-AUD-002',
    module: 'Employee Management',
    subModule: 'Activity Audit',
    feature: 'Filter the activity log by date range, employee name, or action type',
    outcome: 'Auditing a specific incident is efficient without scrolling through unrelated historical entries',
    grouping: 'EM-Audit',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-CRT-001',
    module: 'Item / Inventory Mgmt',
    subModule: 'Item Creation',
    feature: 'Add a new inventory item with SKU code, barcode, unit of measure, and initial stock quantity',
    outcome: 'Every physical item in my warehouse has a unique, trackable digital record',
    grouping: 'IM-Items',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-CRT-002',
    module: 'Item / Inventory Mgmt',
    subModule: 'Item Creation',
    feature: 'Set a low-stock threshold for each item to trigger reorder alerts',
    outcome: 'Stock shortages are flagged before they result in lost sales or broken orders',
    grouping: 'IM-Items',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-LNK-001',
    module: 'Item / Inventory Mgmt',
    subModule: 'Item Linking',
    feature: 'Link an inventory item directly to a product listing on the storefront',
    outcome: 'Every customer order automatically deducts the correct quantity from inventory without manual updates',
    grouping: 'IM-Integration',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-STK-001',
    module: 'Item / Inventory Mgmt',
    subModule: 'Stock Updates',
    feature: 'Manually update the stock quantity of a single item from the item edit screen',
    outcome: 'Inventory stays accurate after physical stock counts, deliveries from suppliers, or damage adjustments',
    grouping: 'IM-Stock',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-STK-002',
    module: 'Item / Inventory Mgmt',
    subModule: 'Stock Updates',
    feature: 'Perform a bulk stock quantity update by uploading a pre-formatted CSV or Excel file',
    outcome: 'Hundreds of stock levels can be corrected after a physical warehouse count in a single operation',
    grouping: 'IM-Stock',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-ALT-001',
    module: 'Item / Inventory Mgmt',
    subModule: 'Alerts',
    feature: "Receive an in-app and/or email notification when any item's stock falls below its defined threshold",
    outcome: 'I replenish stock proactively and never encounter a situation where a popular item is unexpectedly unavailable',
    grouping: 'IM-Alerts',
    custom: 'No',
    setupComments: 'Alert delivery channel configured in notification settings',
    status: 'Open',
  },
  {
    id: 'IM-HIS-001',
    module: 'Item / Inventory Mgmt',
    subModule: 'Stock Movement History',
    feature: 'View a stock movement log for each item showing every in/out entry with date, reason, and quantity',
    outcome: 'I can trace exactly why stock levels changed and detect discrepancies caused by theft or data entry errors',
    grouping: 'IM-History',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'IM-HIS-002',
    module: 'Item / Inventory Mgmt',
    subModule: 'Stock Movement History',
    feature: 'Filter stock movement history by date range or transaction type (order deduction, manual adjustment, import)',
    outcome: 'Investigating a specific inventory discrepancy is fast and precise',
    grouping: 'IM-History',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-DSC-001',
    module: 'Marketing & Promotions',
    subModule: 'Discount Codes',
    feature: 'Create a discount code with a fixed amount or percentage-off value and assign it to specific products or store-wide',
    outcome: 'I can incentivise first-time or returning customers with targeted offers',
    grouping: 'MK-Coupons',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-DSC-002',
    module: 'Marketing & Promotions',
    subModule: 'Discount Codes',
    feature: 'Set a minimum order value and a usage limit (total uses and per-customer uses) on each discount code',
    outcome: 'Promotions remain profitable and cannot be exploited through mass redemptions by one customer',
    grouping: 'MK-Coupons',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-DSC-003',
    module: 'Marketing & Promotions',
    subModule: 'Discount Codes',
    feature: 'Set an expiry date and time for a discount code after which it becomes invalid at checkout',
    outcome: 'Time-limited offers create urgency without requiring manual deactivation',
    grouping: 'MK-Coupons',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-DSC-004',
    module: 'Marketing & Promotions',
    subModule: 'Discount Codes',
    feature: 'View the list of all discount codes with usage count, remaining uses, and expiry status',
    outcome: 'I can monitor code performance and deactivate ineffective codes early',
    grouping: 'MK-Coupons',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-FLS-001',
    module: 'Marketing & Promotions',
    subModule: 'Flash Sales',
    feature: 'Schedule a flash sale on selected products specifying a discounted price and precise start/end date-time',
    outcome: 'Time-sensitive offers go live and expire automatically without any manual intervention at odd hours',
    grouping: 'MK-Sales',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-FLS-002',
    module: 'Marketing & Promotions',
    subModule: 'Flash Sales',
    feature: 'View all active and scheduled flash sales and cancel or extend individual sales',
    outcome: 'I maintain control over promotional pricing and can react quickly to changing business conditions',
    grouping: 'MK-Sales',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-BND-001',
    module: 'Marketing & Promotions',
    subModule: 'Bundle Deals',
    feature: 'Create a bundle deal offering a discounted price when specific products are purchased together',
    outcome: 'Average order value increases as customers are incentivised to buy complementary products',
    grouping: 'MK-Bundles',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'MK-ANL-001',
    module: 'Marketing & Promotions',
    subModule: 'Promotion Analytics',
    feature: 'View a redemption report for each promotion showing total discount given, number of orders generated, and revenue impact',
    outcome: 'I can directly measure the ROI of each promotion and remove ones that discount without driving incremental sales',
    grouping: 'MK-Analytics',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-WDR-001',
    module: 'Financial Operations',
    subModule: 'Withdraw Requests',
    feature: 'View all vendor withdrawal requests filtered by status (Pending, Approved, Denied)',
    outcome: 'Payout requests are processed in a structured queue without any falling through the cracks',
    grouping: 'FN-Withdrawals',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-WDR-002',
    module: 'Financial Operations',
    subModule: 'Withdraw Requests',
    feature: 'Approve a vendor withdrawal request after verifying payment method details',
    outcome: "The vendor's balance is cleared and the payout is logged with a reference for reconciliation",
    grouping: 'FN-Withdrawals',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-WDR-003',
    module: 'Financial Operations',
    subModule: 'Withdraw Requests',
    feature: 'Deny a withdrawal request and provide an admin note explaining the reason',
    outcome: 'Problematic or fraudulent requests are rejected with a documented reason for compliance purposes',
    grouping: 'FN-Withdrawals',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-DSB-001',
    module: 'Financial Operations',
    subModule: 'Store Disbursement',
    feature: 'View the full store disbursement history with lifecycle stages (Pending, Completed, Partially Completed, Cancelled)',
    outcome: 'Every payout batch is traceable from initiation to settlement for audit and compliance purposes',
    grouping: 'FN-Disbursements',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-DLD-001',
    module: 'Financial Operations',
    subModule: 'Delivery Disbursement',
    feature: 'View and process delivery driver disbursements tracking the payment from Processing through Completed',
    outcome: 'Driver payouts are handled in batches with full lifecycle visibility',
    grouping: 'FN-Disbursements',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-COD-001',
    module: 'Financial Operations',
    subModule: 'Collect Cash',
    feature: 'Log a physical cash collection event from a delivery driver or store, specifying amount, payment method, and reference number',
    outcome: 'Every Cash-on-Delivery remittance is recorded digitally, eliminating any gap between physical and digital balances',
    grouping: 'FN-CashCollection',
    custom: 'No',
    setupComments: 'Required when COD is enabled on the platform',
    status: 'Open',
  },
  {
    id: 'FN-COD-002',
    module: 'Financial Operations',
    subModule: 'Collect Cash',
    feature: 'View the complete cash collection log to reconcile physical cash held against digital records',
    outcome: 'Discrepancies between physical cash and system balances are identified and resolved quickly',
    grouping: 'FN-CashCollection',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-MTH-001',
    module: 'Financial Operations',
    subModule: 'Withdraw Methods',
    feature: 'Configure available withdrawal methods (Bank Transfer, Mobile Money, PayPal) and the custom fields required for each',
    outcome: 'Vendors and drivers provide the exact information needed for payout processing, reducing failed transfers',
    grouping: 'FN-Methods',
    custom: 'No',
    setupComments: 'Field examples: IBAN, Swift Code, Account Number, Mobile Number',
    status: 'Open',
  },
  {
    id: 'FN-MTH-002',
    module: 'Financial Operations',
    subModule: 'Withdraw Methods',
    feature: 'Enable, disable, or set a withdrawal method as the default for new requests',
    outcome: 'Outdated payment channels are hidden and the most common method is pre-selected to speed up the process',
    grouping: 'FN-Methods',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
];
