export interface UserStory {
  id: string;
  module: string;
  subModule: string;
  feature: string;
  outcome: string;
  grouping: string;
  custom: string;
  setupComments: string;
  status: string;
}

export const MODULE_COLORS: Record<string, string> = {
  "Product Management": "#EBF5FB",
  "Zone & Module Setup": "#F9EBEA",
  "Business Settings": "#EAECEE",
  "Store Management": "#E8F8F5",
  "Order Management": "#FEF9E7",
  "Flash Sales": "#FEF3CD",
  "Promotion Management": "#F0E6FF",
  "Reports & Analytics": "#F5EEF8",
  "Financial Operations": "#E8DAEF",
};

export const USER_STORIES: UserStory[] = [
  {
    id: 'PM-CAT-001',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'Add a new product category with a name and a 1:1 ratio image in multiple languages (Default, English, Arabic)',
    outcome: 'The category is created and appears in the master category list, enabling products to be assigned to it',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: 'Multilingual name fields (Default / EN / AR) and image upload required',
    status: 'Open',
  },
  {
    id: 'PM-CAT-002',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'View the full category list with search and export controls',
    outcome: 'I can quickly locate any category and export the list to Excel for audit purposes',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CAT-003',
    module: 'Product Management',
    subModule: 'Categories',
    feature: "Edit an existing category's name or image",
    outcome: 'Category information stays accurate without having to delete and recreate entries',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CAT-004',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'Enable or disable a category using a status toggle',
    outcome: 'Hidden categories stop appearing in all product assignment dropdowns and customer storefronts instantly',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CAT-005',
    module: 'Product Management',
    subModule: 'Categories',
    feature: 'Delete a category that has no linked products',
    outcome: 'Stale or test categories are removed, keeping the catalogue clean',
    grouping: 'PM-Categories',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-SUB-001',
    module: 'Product Management',
    subModule: 'Sub Categories',
    feature: 'Add a new sub-category by selecting a parent main category and entering a name in all supported languages',
    outcome: 'Products can be nested under a main category for finer classification, improving shopability',
    grouping: 'PM-SubCat',
    custom: 'No',
    setupComments: 'Parent category must exist before creating sub-category',
    status: 'Open',
  },
  {
    id: 'PM-SUB-002',
    module: 'Product Management',
    subModule: 'Sub Categories',
    feature: 'View the sub-category list showing each sub-category alongside its parent category',
    outcome: 'I can verify the correct parent-child relationships at a glance',
    grouping: 'PM-SubCat',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-SUB-003',
    module: 'Product Management',
    subModule: 'Sub Categories',
    feature: "Edit a sub-category's name or reassign it to a different parent category",
    outcome: 'Mis-classified sub-categories can be corrected without data loss',
    grouping: 'PM-SubCat',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BIM-001',
    module: 'Product Management',
    subModule: 'Categories – Bulk Import',
    feature: 'Download the official category bulk-import Excel template (with or without current data)',
    outcome: 'I have a correctly formatted file to fill in, preventing import errors',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Template must be .xls or .xlsx format',
    status: 'Open',
  },
  {
    id: 'PM-BIM-002',
    module: 'Product Management',
    subModule: 'Categories – Bulk Import',
    feature: 'Upload a completed Excel file to import multiple new categories at once',
    outcome: 'Onboarding large category structures is done in minutes instead of hours of manual entry',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Upload New Data option selected',
    status: 'Open',
  },
  {
    id: 'PM-BIM-003',
    module: 'Product Management',
    subModule: 'Categories – Bulk Import',
    feature: 'Upload a completed Excel file to update existing category records in bulk',
    outcome: 'Mass corrections to names, images, or status are applied without editing each record individually',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Update Existing Data option selected',
    status: 'Open',
  },
  {
    id: 'PM-BEX-001',
    module: 'Product Management',
    subModule: 'Categories – Bulk Export',
    feature: 'Export the full category and sub-category list as an Excel file with optional sort/filter options',
    outcome: 'I have an offline backup or a starting-point file for preparing the next bulk import',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ATT-001',
    module: 'Product Management',
    subModule: 'Attributes',
    feature: 'Add a new product attribute (e.g., Colour, Material, Finish) with multilingual name support',
    outcome: 'Descriptive characteristics can be attached to products, enriching customer-facing detail pages',
    grouping: 'PM-Attributes',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ATT-002',
    module: 'Product Management',
    subModule: 'Attributes',
    feature: 'View all attributes in a list and edit or delete individual attributes',
    outcome: 'The attribute dictionary stays current as product lines evolve',
    grouping: 'PM-Attributes',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-UNT-001',
    module: 'Product Management',
    subModule: 'Units',
    feature: 'Add a new unit of measurement (e.g., kg, piece, metre, litre) with multilingual name support',
    outcome: 'Products can specify the correct selling unit, avoiding customer confusion',
    grouping: 'PM-Units',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-UNT-002',
    module: 'Product Management',
    subModule: 'Units',
    feature: 'View the units list and edit or delete entries',
    outcome: 'Outdated or duplicate units are removed, ensuring only valid options appear in product forms',
    grouping: 'PM-Units',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BRD-001',
    module: 'Product Management',
    subModule: 'Brands',
    feature: 'Add a new brand with a name and an uploaded brand logo',
    outcome: 'Products can be associated with a recognisable brand, building customer trust',
    grouping: 'PM-Brands',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BRD-002',
    module: 'Product Management',
    subModule: 'Brands',
    feature: 'Enable or disable a brand using a status toggle',
    outcome: 'Discontinued brands are hidden from product forms without losing historical data',
    grouping: 'PM-Brands',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BRD-003',
    module: 'Product Management',
    subModule: 'Brands',
    feature: 'View and search the full brand list',
    outcome: 'I can quickly find any brand in a growing catalogue without scrolling',
    grouping: 'PM-Brands',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-001',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Enter product name, short description, and long description in Default, English, and Arabic',
    outcome: 'The product page is fully localised for all supported customer markets',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'All three language tabs should be completed',
    status: 'Open',
  },
  {
    id: 'PM-PRD-002',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Upload a full-size 1:1 product image and a required thumbnail image',
    outcome: 'Customers see a high-quality visual and the thumbnail renders correctly in listing grids',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Thumbnail is mandatory; full image is recommended. Max 100KB, .jpg or .png',
    status: 'Open',
  },
  {
    id: 'PM-PRD-003',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Assign the product to a store, category, sub-category, and brand',
    outcome: 'The product appears in the correct storefront, category page, and brand filter',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Category, Sub-Category and Brand must exist in admin panel BEFORE product can be added',
    status: 'Open',
  },
  {
    id: 'PM-PRD-004',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Select the unit of measurement and set a maximum purchase quantity limit per order',
    outcome: 'Customers buy the correct measured unit and bulk purchases beyond the limit are blocked at checkout',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-005',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Set the product price, current stock quantity, and a discount percentage',
    outcome: 'The price, discounted price, and remaining stock are displayed accurately on the customer app',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-006',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Add product attributes and fill in the variant price/stock table for each combination',
    outcome: 'Customers can choose a variant (e.g., size or colour) and the correct price and stock are shown',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PRD-007',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Import product information from the platform gallery to pre-fill image fields',
    outcome: 'Reusing existing gallery assets avoids duplicate uploads and speeds up listing',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Add Info From Gallery feature',
    status: 'Open',
  },
  {
    id: 'PM-PRD-008',
    module: 'Product Management',
    subModule: 'Product Setup – Add New',
    feature: 'Add searchable keyword tags to the product',
    outcome: 'Customers find the product through relevant search terms on the customer app',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-001',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'View the complete product list with search, filter by category/status/store/zone, and paginate results',
    outcome: 'I can find any product instantly even with thousands of SKUs',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-002',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'Edit any field of an existing product directly from the list view',
    outcome: 'Corrections to price, stock, descriptions, or images are applied without re-creating the listing',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-003',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'Enable or disable a product using the status toggle',
    outcome: 'Out-of-season or out-of-stock products are hidden from customers without permanent deletion',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LST-004',
    module: 'Product Management',
    subModule: 'Product Setup – List',
    feature: 'Delete a product permanently from the catalogue',
    outcome: 'Discontinued SKUs are removed cleanly, freeing up catalogue space',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: 'Action is irreversible',
    status: 'Open',
  },
  {
    id: 'PM-LOW-001',
    module: 'Product Management',
    subModule: 'Product Setup – Low Stock',
    feature: 'View a filtered list of all products whose stock is at or below threshold, filter by zone or store',
    outcome: 'I can prioritise reordering before products go out of stock and cause lost sales',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-LOW-002',
    module: 'Product Management',
    subModule: 'Product Setup – Low Stock',
    feature: 'Update the stock quantity of a low-stock product directly from the low-stock list',
    outcome: 'I can top up inventory without navigating through the full product editor',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-REV-001',
    module: 'Product Management',
    subModule: 'Product Setup – Reviews',
    feature: 'View all customer reviews submitted for products, including rating, comment, and reviewer name',
    outcome: 'I have visibility over product satisfaction across the entire catalogue',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-REV-002',
    module: 'Product Management',
    subModule: 'Product Setup – Reviews',
    feature: 'Delete an inappropriate or fraudulent product review',
    outcome: 'Fake or abusive reviews are removed before they damage product reputation',
    grouping: 'PM-ProductSetup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-PIB-001',
    module: 'Product Management',
    subModule: 'Product Setup – Bulk Import',
    feature: 'Download the product bulk-import Excel template pre-filled with existing product data',
    outcome: 'I can use the exported file as a base for updates rather than starting from scratch',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Category, Sub-Category, Brand must exist before importing products',
    status: 'Open',
  },
  {
    id: 'PM-PIB-002',
    module: 'Product Management',
    subModule: 'Product Setup – Bulk Import',
    feature: 'Import a filled Excel file to add hundreds of new products in a single operation',
    outcome: 'Mass product onboarding is completed in minutes with zero manual form filling',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: 'Only .xls/.xlsx accepted; image file names must not exceed 30 characters',
    status: 'Open',
  },
  {
    id: 'PM-PEX-001',
    module: 'Product Management',
    subModule: 'Product Setup – Bulk Export',
    feature: 'Export the full product catalogue to Excel for reporting, backup, or external sharing',
    outcome: 'I always have an up-to-date offline copy of the product database for compliance or handover',
    grouping: 'PM-BulkOps',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-001',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Draw a new operational zone boundary on the interactive Google Map and name it in multiple languages',
    outcome: 'A precise geographic service area is defined so stores and deliveries can be restricted to that region',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: 'Both polygon drawing and zone name are mandatory',
    status: 'Open',
  },
  {
    id: 'ZN-002',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'View, search, and export all existing zones in the zone management list',
    outcome: 'I have a clear overview of every service region and can audit them at any time',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-003',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Enable or disable an entire zone using the master status toggle',
    outcome: 'All storefronts, deliveries, and customer access in a problematic region can be suspended instantly',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: 'Disabling a zone removes it from the customer app in real time',
    status: 'Open',
  },
  {
    id: 'ZN-004',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Connect a business module to a zone using the grid action icon',
    outcome: 'The zone starts offering the selected type of services (e.g., eCommerce) to customers in that area',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: 'A zone without a connected module offers no services',
    status: 'Open',
  },
  {
    id: 'ZN-005',
    module: 'Zone & Module Setup',
    subModule: 'Zone Setup',
    feature: 'Edit the drawn boundary polygon of an existing zone or delete obsolete zones via the three-dot menu',
    outcome: 'Service area adjustments are reflected immediately without recreating the zone from scratch',
    grouping: 'ZN-Setup',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-001',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: 'Create a new business module type (Grocery, Food, Pharmacy, eCommerce, Parcel) with name, description, icon, and thumbnail',
    outcome: 'A new vertical is available for stores to register under and for customers to browse on the home screen',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: 'Module type cannot be changed after creation',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-002',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: 'Filter the module list by module type and search by name; export the module list',
    outcome: 'I can locate specific modules instantly as the platform scales to many business verticals',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-003',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: 'Enable or disable a business module to control its visibility on the customer app home screen',
    outcome: 'A module under maintenance or review is hidden until it is ready',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: 'Disabling hides all stores under this module',
    status: 'Open',
  },
  {
    id: 'ZN-MOD-004',
    module: 'Zone & Module Setup',
    subModule: 'Module Setup',
    feature: "Edit a module's name, description, icon, or thumbnail after initial creation",
    outcome: 'Branding and descriptions stay accurate as the business evolves without recreating the module',
    grouping: 'ZN-Module',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-001',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Set global company name, email, phone, country, address, and map coordinates as platform defaults',
    outcome: 'All receipts, emails, and the customer app default map reflect the correct company identity',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Latitude and longitude set the default map centre for new users',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-002',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Upload the platform logo (3:1 ratio) and favicon (1:1 ratio)',
    outcome: 'The brand identity is consistently displayed across the admin dashboard, web portal, and browser tabs',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-003',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Configure time zone, time format, currency symbol, currency position, decimal precision, copyright, and cookies text',
    outcome: 'All financial figures, order timestamps, and footer text reflect the correct local standards',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Currency and decimal changes affect all displayed prices immediately',
    status: 'Open',
  },
  {
    id: 'BS-BIZ-004',
    module: 'Business Settings',
    subModule: 'Business Information',
    feature: 'Activate Maintenance Mode to disable all customer-facing apps and APIs during critical updates',
    outcome: 'Customers see a maintenance screen and cannot place orders during planned downtime, protecting data integrity',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Only Admin panel remains accessible in maintenance mode',
    status: 'Open',
  },
  {
    id: 'BS-VND-001',
    module: 'Business Settings',
    subModule: 'Vendor Settings',
    feature: 'Enable or disable vendor self-registration, configure order cancellation, product approval, review replies, and cash-in-hand limits',
    outcome: 'All vendor operational policies are enforced consistently from a single settings page',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Product approval scope: Add new / Update price / Update details',
    status: 'Open',
  },
  {
    id: 'BS-DLV-001',
    module: 'Business Settings',
    subModule: 'Deliveryman Settings',
    feature: 'Configure driver settings: tips, earnings display, self-registration, maximum orders, delivery photo proof, and cash-in-hand overflow',
    outcome: 'Fleet policies are enforced consistently and drivers cannot accept more jobs than they can safely handle',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Photo proof requires driver to upload an image before marking order Delivered',
    status: 'Open',
  },
  {
    id: 'BS-CUS-001',
    module: 'Business Settings',
    subModule: 'Customer & Wallet',
    feature: 'Configure customer wallet, referral program, refund to wallet, loyalty points earning rate, and minimum redemption threshold',
    outcome: 'Customers are rewarded for loyalty and referrals, and all wallet features are centrally managed',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Example: 2% earn rate, 100 points = 1 BHD, minimum 500 points to redeem',
    status: 'Open',
  },
  {
    id: 'BS-REF-001',
    module: 'Business Settings',
    subModule: 'Refund Settings',
    feature: 'Enable or disable the global refund request feature and manage the list of refund reason options',
    outcome: 'Refund data is categorised accurately for analytics and only open when operational capacity allows',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Examples: Damaged item, Missing item, Wrong order',
    status: 'Open',
  },
  {
    id: 'BS-LNG-001',
    module: 'Business Settings',
    subModule: 'Language Setup',
    feature: 'Add a new platform language with ISO code and text direction (LTR or RTL), and set the default language',
    outcome: 'The platform is accessible in a new language market and first-time visitors see the most appropriate language',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'RTL setting flips the entire app UI for Arabic/Hebrew',
    status: 'Open',
  },
  {
    id: 'BS-TAX-001',
    module: 'Business Settings',
    subModule: 'System Tax',
    feature: 'Create a new tax type with name and percentage rate, and configure inclusive/exclusive calculation method',
    outcome: 'Taxes are available for assignment to orders and products, ensuring regulatory compliance',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Configured separately for Order Module and Parcel Module',
    status: 'Open',
  },
  {
    id: 'BS-SUB-001',
    module: 'Business Settings',
    subModule: 'Subscription Management',
    feature: 'Create subscription packages with name, price, validity period, and available features checklist (POS, self-delivery, app access, reviews, chat)',
    outcome: 'Vendors are offered tiered plans that gate features based on their subscription level',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Features: POS, self-delivery, app access, reviews, chat',
    status: 'Open',
  },
  {
    id: 'BS-SUB-002',
    module: 'Business Settings',
    subModule: 'Subscription Management',
    feature: 'Configure free trial period, deadline warning message, and return money restriction threshold',
    outcome: 'New vendors can evaluate the platform risk-free and are warned before their plan expires',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-PGS-001',
    module: 'Business Settings',
    subModule: 'Pages & Social Media',
    feature: 'Edit all legal and informational pages (Terms & Conditions, Privacy Policy, Refund Policy, Cancellation Policy, About Us) using the rich-text editor',
    outcome: 'All legal pages are always up to date, visible to customers, and support multilingual content',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Refund Policy and Cancellation Policy pages have a STATUS toggle to enable/disable visibility',
    status: 'Open',
  },
  {
    id: 'BS-PGS-002',
    module: 'Business Settings',
    subModule: 'Pages & Social Media',
    feature: 'Add or update social media links (Facebook, Instagram, Twitter, LinkedIn, etc.) shown in the platform footer',
    outcome: 'Customers can follow the brand on their preferred social channel directly from the app or website',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-LND-001',
    module: 'Business Settings',
    subModule: 'Landing Page',
    feature: 'Edit the React customer web landing page: header, subtitle, tag line, company intro, download app section, promotional banners, business section, testimonials',
    outcome: 'The public-facing web portal reflects current promotions and brand messaging accurately',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'All content supports Default/EN/AR language tabs',
    status: 'Open',
  },
  {
    id: 'BS-GAL-001',
    module: 'Business Settings',
    subModule: 'Gallery',
    feature: 'Browse the centralised gallery file explorer organised into system folders (Products, Store, Banner, Category, etc.)',
    outcome: 'I can locate any uploaded file quickly without searching through individual sections',
    grouping: 'BS-Gallery',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-GAL-002',
    module: 'Business Settings',
    subModule: 'Gallery',
    feature: 'Upload individual images or a zip archive of multiple images to any gallery folder',
    outcome: 'New visual assets are stored centrally and available to reuse across the entire platform',
    grouping: 'BS-Gallery',
    custom: 'No',
    setupComments: 'Zip upload auto-extracts all contained images',
    status: 'Open',
  },
  {
    id: 'BS-GAL-003',
    module: 'Business Settings',
    subModule: 'Gallery',
    feature: 'Open a gallery folder, click any image to preview it, then copy its direct URL or download it',
    outcome: 'Asset URLs can be shared or embedded in external tools without leaving the admin panel',
    grouping: 'BS-Gallery',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'BS-WBS-001',
    module: 'Business Settings',
    subModule: 'Websocket Config',
    feature: 'Configure the websocket server URL and port for real-time order tracking and push notifications',
    outcome: 'Live driver tracking on the map and instant alerts function correctly for all app users',
    grouping: 'BS-Settings',
    custom: 'No',
    setupComments: 'Only change with DevOps guidance; errors break live tracking',
    status: 'Open',
  },
  {
    id: 'SM-NEW-001',
    module: 'Store Management',
    subModule: 'New Store Requests',
    feature: 'View pending vendor store joining applications and denied applications across two status tabs',
    outcome: 'All vendor applications are reviewed in a structured queue without any falling through the cracks',
    grouping: 'SM-Onboarding',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'SM-NEW-002',
    module: 'Store Management',
    subModule: 'New Store Requests',
    feature: 'Approve or deny a pending store application using action icons on the request list',
    outcome: 'Approved stores immediately become active and visible to customers; denied stores receive a rejection',
    grouping: 'SM-Onboarding',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'SM-ADD-001',
    module: 'Store Management',
    subModule: 'Add Store',
    feature: 'Manually create a store by filling in store name, address, logo, cover image, delivery time, zone, GPS coordinates, owner details, email, password, and business TIN',
    outcome: 'A fully operational storefront is created instantly without waiting for a vendor self-registration',
    grouping: 'SM-Onboarding',
    custom: 'No',
    setupComments: 'Logo must be 1:1; Cover must be 2:1 ratio',
    status: 'Open',
  },
  {
    id: 'SM-LST-001',
    module: 'Store Management',
    subModule: 'Stores List',
    feature: 'View the paginated list of all accepted stores with search and actions (View, Edit, Delete)',
    outcome: 'I have a full overview of every active vendor on the platform and can manage any store quickly',
    grouping: 'SM-Stores',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'SM-LST-002',
    module: 'Store Management',
    subModule: 'Stores List',
    feature: "Toggle a store's Featured status to promote it on the customer website homepage",
    outcome: 'Selected stores gain premium homepage placement, increasing their order volume',
    grouping: 'SM-Stores',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'SM-LST-003',
    module: 'Store Management',
    subModule: 'Stores List',
    feature: "Enable or disable a store's active Status using the toggle in the stores list",
    outcome: 'Suspended stores are immediately hidden from all customer-facing apps and cannot receive new orders',
    grouping: 'SM-Stores',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'SM-REC-001',
    module: 'Store Management',
    subModule: 'Recommended Stores',
    feature: 'View and manage the list of recommended stores with rating, total products, total orders, and status',
    outcome: 'Customers see a curated selection of high-performing stores on the platform',
    grouping: 'SM-Stores',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'SM-BIM-001',
    module: 'Store Management',
    subModule: 'Store Bulk Import',
    feature: 'Download the store bulk-import Excel template and upload it to create or update multiple stores at once',
    outcome: 'Large-scale store onboarding is completed in minutes without individual form submissions',
    grouping: 'SM-BulkOps',
    custom: 'No',
    setupComments: 'Download template first; fill; then Upload New Data or Update Existing Data',
    status: 'Open',
  },
  {
    id: 'SM-BEX-001',
    module: 'Store Management',
    subModule: 'Store Bulk Export',
    feature: 'Export all store records as an Excel file',
    outcome: 'An offline backup of all store data is available for audits or sharing with management',
    grouping: 'SM-BulkOps',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-POS-001',
    module: 'Order Management',
    subModule: 'POS – Point of Sale',
    feature: 'Open the POS system, select a store and category, then search for and add products to the cart',
    outcome: 'Walk-in and offline customers can be served immediately without them needing the app',
    grouping: 'OM-POS',
    custom: 'No',
    setupComments: 'POS requires a Subscription Plan that includes POS feature',
    status: 'Open',
  },
  {
    id: 'OM-POS-002',
    module: 'Order Management',
    subModule: 'POS – Point of Sale',
    feature: 'Link the POS order to an existing customer account or create a new customer on the spot',
    outcome: 'Every sale is recorded against a customer for order history and loyalty tracking',
    grouping: 'OM-POS',
    custom: 'No',
    setupComments: 'New customer: First Name, Last Name, Email, Phone',
    status: 'Open',
  },
  {
    id: 'OM-POS-003',
    module: 'Order Management',
    subModule: 'POS – Point of Sale',
    feature: 'Review the POS order summary, select a payment method, and place the order or clear the cart',
    outcome: 'The sale is processed and logged in the order system with full financial detail',
    grouping: 'OM-POS',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-001',
    module: 'Order Management',
    subModule: 'Order List',
    feature: 'View all orders organised by status categories: All Orders, Scheduled, Pending, Accepted, Processing, Order On The Way, Delivered, Cancelled, Payment Failed, Refunded',
    outcome: 'I have full visibility of every transaction in a single view without missing any incoming order',
    grouping: 'OM-Orders',
    custom: 'No',
    setupComments: 'Correct status stages: Pending → Accepted → Processing → Order On The Way → Delivered',
    status: 'Open',
  },
  {
    id: 'OM-ORD-002',
    module: 'Order Management',
    subModule: 'Order List',
    feature: 'Filter orders by each of the 9 status categories using the sidebar tabs',
    outcome: 'I see only the orders requiring action at each stage of the fulfilment workflow',
    grouping: 'OM-Orders',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-003',
    module: 'Order Management',
    subModule: 'Order Details',
    feature: 'Open the full order detail view by clicking the Eye icon; see order summary, all line items, financial breakdown, customer details, delivery info, driver proof photo, and store info',
    outcome: 'I have all information needed to resolve any issue or fulfil the order correctly without contacting the customer',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-ORD-004',
    module: 'Order Management',
    subModule: 'Order Details',
    feature: 'Update the order status to the next stage and assign a delivery driver from the order detail Edit screen',
    outcome: 'Each status update triggers a customer notification and keeps the fulfilment pipeline moving forward',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: 'Click Eye icon → Edit → Update Status / Assign Delivery Man',
    status: 'Open',
  },
  {
    id: 'OM-ORD-005',
    module: 'Order Management',
    subModule: 'Order Details',
    feature: 'Print the order invoice by clicking the Printer icon on the order row',
    outcome: 'A properly formatted receipt or PDF is generated for the customer or for accounting reconciliation',
    grouping: 'OM-Processing',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-OFP-001',
    module: 'Order Management',
    subModule: 'Offline Payments',
    feature: 'View customer offline payment submissions across All, Pending, Verified, and Denied status tabs',
    outcome: 'Manual payment evidence is reviewed in a structured queue without missing any submission',
    grouping: 'OM-Payments',
    custom: 'No',
    setupComments: 'Always confirm funds received in bank before marking Verified',
    status: 'Open',
  },
  {
    id: 'OM-OFP-002',
    module: 'Order Management',
    subModule: 'Offline Payments',
    feature: "Update an offline payment status to Verified or Denied after reviewing the customer's uploaded proof",
    outcome: 'Payment status is resolved and the order can proceed; customer is notified of the outcome',
    grouping: 'OM-Payments',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'OM-REF-001',
    module: 'Order Management',
    subModule: 'Order Refunds',
    feature: 'View and action customer refund requests by clicking Approve or Rejected for each request',
    outcome: 'Refund decisions are documented and processed within the system without manual email exchanges',
    grouping: 'OM-Returns',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FS-CRT-001',
    module: 'Flash Sales',
    subModule: 'Flash Sale Creation',
    feature: 'Create a new Flash Sale with a title (in all languages), Admin Discount %, Store Discount % split, Start Date, and End Date',
    outcome: 'A time-limited promotional sale is scheduled and will activate automatically on the set date',
    grouping: 'FS-Create',
    custom: 'No',
    setupComments: 'Flash Sales are ADMIN-ONLY. Vendors cannot create flash sales.',
    status: 'Open',
  },
  {
    id: 'FS-PRD-001',
    module: 'Flash Sales',
    subModule: 'Flash Sale Products',
    feature: 'Add products to an existing flash sale by selecting the item, setting the sale stock quantity, and setting the discount percentage',
    outcome: 'Only the specified products appear at their discounted price during the flash sale window',
    grouping: 'FS-Products',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FS-MGT-001',
    module: 'Flash Sales',
    subModule: 'Flash Sale Management',
    feature: 'Publish, edit, or delete flash sales from the Flash Sale List using the toggle and action icons',
    outcome: 'I can control exactly which flash sales are visible to customers and adjust or remove them as needed',
    grouping: 'FS-Manage',
    custom: 'No',
    setupComments: 'Toggle Publish controls customer visibility without deleting the sale',
    status: 'Open',
  },
  {
    id: 'PM-BCM-001',
    module: 'Promotion Management',
    subModule: 'Basic Campaigns',
    feature: 'Create a Basic Campaign with name, short description (in all languages), start/end dates, daily time schedule, and a 900x300 banner image',
    outcome: 'A time-scheduled promotional campaign with a banner goes live on the customer app automatically',
    grouping: 'PM-Campaigns',
    custom: 'No',
    setupComments: 'Banner must be 900x300 pixels',
    status: 'Open',
  },
  {
    id: 'PM-BCM-002',
    module: 'Promotion Management',
    subModule: 'Basic Campaigns',
    feature: 'View all basic campaigns in the Campaign List',
    outcome: 'I have an overview of every scheduled and active basic campaign without navigating multiple screens',
    grouping: 'PM-Campaigns',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ICM-001',
    module: 'Promotion Management',
    subModule: 'Item Campaigns',
    feature: 'Create an Item Campaign by selecting a store and item, adding attributes, uploading a 1:1 image, and setting start/end date with daily time schedule',
    outcome: 'A product-specific campaign is promoted to customers with a custom image and precise scheduling',
    grouping: 'PM-Campaigns',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ICM-002',
    module: 'Promotion Management',
    subModule: 'Item Campaigns',
    feature: 'View all item campaigns in the Item Campaign List',
    outcome: 'I can monitor and manage all individual product promotions from a single list',
    grouping: 'PM-Campaigns',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-BNR-001',
    module: 'Promotion Management',
    subModule: 'Banners',
    feature: 'Add a promotional banner by filling in the title (in all languages), selecting a zone, banner type (store-wise, item-wise, or default), selecting a store, and uploading a 3:1 image',
    outcome: 'The banner appears on the customer app in the correct zone and context with professional imagery',
    grouping: 'PM-Banners',
    custom: 'No',
    setupComments: 'Banner image must be 3:1 ratio',
    status: 'Open',
  },
  {
    id: 'PM-BNR-002',
    module: 'Promotion Management',
    subModule: 'Banners',
    feature: 'View the banner list with status toggle, edit, and delete options',
    outcome: 'All active banners are managed from a central list with immediate enable/disable control',
    grouping: 'PM-Banners',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-OBN-001',
    module: 'Promotion Management',
    subModule: 'Other Banners',
    feature: 'Upload themed banners for three specific website sections: Best Reviewed Items (235x346), New Arrivals (235x346), and Bottom Section Banner (5:1 ratio)',
    outcome: 'The customer website has consistent, correctly-sized promotional imagery in all designated banner slots',
    grouping: 'PM-Banners',
    custom: 'No',
    setupComments: 'Each section has a specific size requirement',
    status: 'Open',
  },
  {
    id: 'PM-CPN-001',
    module: 'Promotion Management',
    subModule: 'Coupons',
    feature: 'Create a coupon with title, type, store, customer selection, unique code, usage limit, start/expiry dates, discount type (amount or percent), minimum purchase, and maximum discount amount',
    outcome: 'Customers can redeem the coupon at checkout and the discount is applied automatically within the configured rules',
    grouping: 'PM-Coupons',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-CPN-002',
    module: 'Promotion Management',
    subModule: 'Coupons',
    feature: 'View the coupon list with status toggle, edit, and delete options',
    outcome: 'All coupons are managed centrally and can be activated or retired instantly',
    grouping: 'PM-Coupons',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-NTF-001',
    module: 'Promotion Management',
    subModule: 'Push Notifications',
    feature: 'Send a push notification by filling in the title, selecting a zone, choosing recipients (all customers, new customers, etc.), entering a description, and uploading an image',
    outcome: 'Targeted push notifications reach the intended customer segment in the selected zone instantly',
    grouping: 'PM-Notifications',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-NTF-002',
    module: 'Promotion Management',
    subModule: 'Push Notifications',
    feature: 'View the notification history list with edit and delete options',
    outcome: 'All sent push notifications are logged and can be reviewed or removed as needed',
    grouping: 'PM-Notifications',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'PM-ADV-001',
    module: 'Promotion Management',
    subModule: 'Advertisements',
    feature: 'Create an admin advertisement with title, short description, store, priority, ad type, validity dates, review & rating display options, a 1:1 image, and a 2:1 cover image',
    outcome: 'The advertisement is displayed on the customer app with a live preview shown during setup',
    grouping: 'PM-Ads',
    custom: 'No',
    setupComments: 'A live preview is shown during ad creation',
    status: 'Open',
  },
  {
    id: 'PM-ADV-002',
    module: 'Promotion Management',
    subModule: 'Advertisements',
    feature: 'Review advertisement requests submitted by vendors across New Requests, Update Requests, and Denied Requests tabs, then approve or deny each',
    outcome: 'Vendor ad requests are moderated before they reach customers, maintaining platform quality standards',
    grouping: 'PM-Ads',
    custom: 'No',
    setupComments: 'Vendors submit ad requests; admin approves/denies. There is no self-serve ad analytics.',
    status: 'Open',
  },
  {
    id: 'PM-ADV-003',
    module: 'Promotion Management',
    subModule: 'Advertisements',
    feature: 'View the full Ads List showing all currently active advertisements',
    outcome: 'I have visibility of every live advertisement on the platform from a single list',
    grouping: 'PM-Ads',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-TXN-001',
    module: 'Reports & Analytics',
    subModule: 'Transaction Report',
    feature: 'View the Transaction Report filtered by module, zone, store, and time duration; see summary cards for Admin Earning, Store Earning, Deliveryman Earning, Completed Transactions, and Refunded Transactions',
    outcome: 'Every monetary movement is auditable and all stakeholder earnings are summarised without manual calculation',
    grouping: 'RA-Transactions',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-TXN-002',
    module: 'Reports & Analytics',
    subModule: 'Transaction Report',
    feature: 'View and export the Order Transactions detail table; download individual order statements or export all as CSV or Excel',
    outcome: 'Reports are available in standard formats for accountants, partners, or management decks',
    grouping: 'RA-Transactions',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-ITM-001',
    module: 'Reports & Analytics',
    subModule: 'Item Report',
    feature: 'View the Item Report filtered by module, store, zone, time, and category; see sell count, revenue, discount given, average sale value, and average ratings per item',
    outcome: 'I can identify top-performing and underperforming products to guide restocking and marketing decisions',
    grouping: 'RA-Items',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-STW-001',
    module: 'Reports & Analytics',
    subModule: 'Store Wise Report',
    feature: 'View the Store Wise Report across three sections: Summary Report (total orders, avg order value, payment breakdown), Sales Report (gross sale, tax, commission, quantity, discount), and Order Report (discount, coupon, cancelled, incomplete, completed counts)',
    outcome: 'Per-store performance is fully visible from financial, sales, and order fulfilment perspectives',
    grouping: 'RA-Stores',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-EXP-001',
    module: 'Reports & Analytics',
    subModule: 'Expense Report',
    feature: 'View the Expense Report filtered by module, zone, vendor, customer, time, and expense type (Add fund bonus, Free delivery, Coupon discount, Flash sale discount, CashBack, Referral Discount); export the expense list',
    outcome: 'All platform-funded expenses are tracked by type, enabling accurate profitability analysis',
    grouping: 'RA-Expenses',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-DSB-001',
    module: 'Reports & Analytics',
    subModule: 'Disbursement Report',
    feature: 'View the Disbursement Report for Stores and Delivery Men with summary cards (Pending, Completed, Cancelled counts) and a detailed filtered table; export available',
    outcome: 'All payout batches are traceable from initiation to settlement for both vendors and drivers',
    grouping: 'RA-Disbursements',
    custom: 'No',
    setupComments: 'Two tabs: Stores and Deliverymen',
    status: 'Open',
  },
  {
    id: 'RA-ORD-001',
    module: 'Reports & Analytics',
    subModule: 'Order Report',
    feature: 'View the Order Report filtered by modules, zones, stores, customers, and time; see statistics cards (Total, In Progress, On The Way, Delivered, Failed, Refunded, Cancelled) and a full order table; export to Excel; view invoice previews',
    outcome: 'A complete order performance overview is available for any time period and business segment',
    grouping: 'RA-Orders',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-ATX-001',
    module: 'Reports & Analytics',
    subModule: 'Admin Tax Report',
    feature: 'Generate the Admin Tax Report by selecting a date range and choosing between Same Tax for All Income Source or Different Tax for Different Income Source; view total income and total tax broken down by income source',
    outcome: 'Tax obligations are calculated accurately and presented in a format ready for accounting or government submission',
    grouping: 'RA-Tax',
    custom: 'No',
    setupComments: 'Two methods: Same Tax for All, or Different Tax by Income Source',
    status: 'Open',
  },
  {
    id: 'RA-VTX-001',
    module: 'Reports & Analytics',
    subModule: 'Vendor Tax Report',
    feature: 'View the Vendor Tax Report filtered by date range and specific store; see total orders, total order amount, and total tax amount per vendor',
    outcome: 'Tax contributions from each vendor are traceable and reportable for regulatory compliance',
    grouping: 'RA-Tax',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'RA-PTX-001',
    module: 'Reports & Analytics',
    subModule: 'Parcel Tax Report',
    feature: 'View the Parcel Tax Report filtered by date range; see total orders, total order amount, and tax amount for parcel delivery services; export available',
    outcome: 'Tax obligations specific to the parcel delivery module are tracked separately from e-commerce orders',
    grouping: 'RA-Tax',
    custom: 'No',
    setupComments: 'Parcel module only',
    status: 'Open',
  },
  {
    id: 'FN-WDR-001',
    module: 'Financial Operations',
    subModule: 'Withdraw Requests',
    feature: 'View all vendor withdrawal requests filtered by status (Pending, Approved, Denied)',
    outcome: 'Payout requests are processed in a structured queue without any falling through the cracks',
    grouping: 'FN-Withdrawals',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-WDR-002',
    module: 'Financial Operations',
    subModule: 'Withdraw Requests',
    feature: 'Approve a vendor withdrawal request after verifying payment method details',
    outcome: "The vendor's balance is cleared and the payout is logged with a reference for reconciliation",
    grouping: 'FN-Withdrawals',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-WDR-003',
    module: 'Financial Operations',
    subModule: 'Withdraw Requests',
    feature: 'Deny a withdrawal request and provide an admin note explaining the reason',
    outcome: 'Problematic or fraudulent requests are rejected with a documented reason for compliance purposes',
    grouping: 'FN-Withdrawals',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-DSB-001',
    module: 'Financial Operations',
    subModule: 'Store Disbursement',
    feature: 'View the full store disbursement history with lifecycle stages (Pending, Completed, Cancelled) and filter by status',
    outcome: 'Every payout batch is traceable from initiation to settlement for audit and compliance purposes',
    grouping: 'FN-Disbursements',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-DLD-001',
    module: 'Financial Operations',
    subModule: 'Delivery Man Disbursement',
    feature: 'View and process delivery driver disbursements tracking the payment through the full lifecycle (Pending, Processing, Completed)',
    outcome: 'Driver payouts are handled in batches with full lifecycle visibility',
    grouping: 'FN-Disbursements',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-COD-001',
    module: 'Financial Operations',
    subModule: 'Collect Cash',
    feature: 'Log a physical cash collection event from a delivery driver or store, specifying amount, payment method, and reference number',
    outcome: 'Every Cash-on-Delivery remittance is recorded digitally, eliminating any gap between physical and digital balances',
    grouping: 'FN-CashCollection',
    custom: 'No',
    setupComments: 'Required when COD is enabled on the platform',
    status: 'Open',
  },
  {
    id: 'FN-COD-002',
    module: 'Financial Operations',
    subModule: 'Collect Cash',
    feature: 'View the complete cash collection log to reconcile physical cash held against digital records',
    outcome: 'Discrepancies between physical cash and system balances are identified and resolved quickly',
    grouping: 'FN-CashCollection',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-DPM-001',
    module: 'Financial Operations',
    subModule: 'Delivery Man Payments',
    feature: 'Log an ad hoc bonus payment directly to a delivery driver outside the automated disbursement cycle',
    outcome: 'Exceptional payments such as bonuses or corrections are recorded and traceable in the system',
    grouping: 'FN-Payments',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
  {
    id: 'FN-MTH-001',
    module: 'Financial Operations',
    subModule: 'Withdraw Methods',
    feature: 'Configure available withdrawal methods (Bank Transfer, Mobile Money, etc.) and the custom fields required for each',
    outcome: 'Vendors and drivers provide the exact information needed for payout processing, reducing failed transfers',
    grouping: 'FN-Methods',
    custom: 'No',
    setupComments: 'Field examples: IBAN, Swift Code, Account Number, Mobile Number',
    status: 'Open',
  },
  {
    id: 'FN-MTH-002',
    module: 'Financial Operations',
    subModule: 'Withdraw Methods',
    feature: 'Enable, disable, or set a withdrawal method as the default for new requests',
    outcome: 'Outdated payment channels are hidden and the most common method is pre-selected to speed up the process',
    grouping: 'FN-Methods',
    custom: 'No',
    setupComments: '',
    status: 'Open',
  },
];
